#!/bin/bash
#
#----------------------------------------------#
# Contributor: Tobias Holzmann                 #
# Last Change: November                        #
# Topic:                                       #
# Email:       Tobias.Holzmann@Holzmann-cfd.de #
#----------------------------------------------#


#-------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear


#-------------------------------------------------------------------------------
foamCleanTutorials
rm -rf constant/triSurface/*.eMesh 
rm -rf 0 log* constant/extend*


#-------------------------------------------------------------------------------
