#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  15 September 2018                  #
# Updated for OF-6: 25 February 2020 by A Fiedler #
#-------------------------------------------------#
# Topic:       Adaptive mesh refinement           #
# OpenFOAM:    4.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-6"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Create surface feature edges"
surfaceFeatureExtract >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Change boundary types of front and back"
changeDictionary >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Prepare and clean case for adaptive mesh refinement"
rm -r 0 const*/polyMesh/refine*


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to 0"
cp -r 0.org 0


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n"


#------------------------------------------------------------------------------
echo -e "\n
Start simulation
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Call pimpleFoam and start the simulation (~10 - 20 minutes)"
pimpleFoam > logSimulation


#------------------------------------------------------------------------------
echo -e "   - Simulation finished, use 'paraFoam' to check the results"


#------------------------------------------------------------------------------
